version: '3.7'

x-tests: &tests
  image: zerlok/python-bugs/tests:latest
  build:
    context: .
    dockerfile: Dockerfile
    target: development
  depends_on:
    - postgres
  environment:
    DATABASE: postgresql+asyncpg://user:pass@postgres:5432/test-db
    SCHEMA: test-schema
  entrypoint: sh
  command: -c 'poetry run wait-for-it --service $${DATABASE} && poetry run pytest'

services:
  postgres:
    image: postgres:11.10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-db
    command: postgres -c max_connections=20 -c shared_buffers=200MB

  poetry:
    image: zerlok/python-bugs/poetry:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: poetry

  test-sqlalchemy-enum:
    <<: *tests
